### ISSUE TITLE
Can't run two animations at once

### ISSUE THREAD

**Issue by travisryan** [proyecto26/animatable-component#10]
I have to animations I try to run, and both start according to events, but only one finishes. I'm not getting any errors back.

```
if(self.animatePlayerTo != null)
      {
        var animatePlayerTo = document.getElementById("animate"+self.animatePlayerTo);
        console.log(animatePlayerTo);
        animatePlayerTo.addEventListener("start", function(event) {
          console.log('ANIMATION START', event)
        });
        animatePlayerTo.addEventListener("finish", function(event) {
          console.log('ANIMATION FINISH', event)
        });
        await animatePlayerTo.play();
        //self.animatePlayerTo = null;
      }
      if(self.animatePlayerFrom != null)
      {
        var animatePlayerFrom = document.getElementById("animate"+self.animatePlayerFrom);
        console.log(animatePlayerFrom);
        animatePlayerFrom.addEventListener("start", function(event2) {
          console.log('ANIMATION START', event2)
        });
        animatePlayerFrom.addEventListener("finish", function(event2) {
          console.log('ANIMATION FINISH', event2)
        });
        await animatePlayerFrom.play();
        //self.animatePlayerFrom = null;
      }
```
Console proof...
[https://imgur.com/hOjGct7](url)

**Comment by jdnichollsc** [comment]
Hello! Can you share a reproducible demo from Codepen? Check this base if you want to fork => https://codepen.io/jdnichollsc/pen/MWwpGNW
Let me know :)

**Comment by travisryan** [comment]
well I tried... never used codepen. In my own code I'm using Ionic. I can make one work fine.


https://codepen.io/travisryan/pen/jOPLWKY

**Comment by jdnichollsc** [comment]
@travisryan ohhh are you using Ionic with Angular? Try this instead:
```
<animatable-component
  autoPlay
  animation="heartBeat"
  iterations="Infinity"
  easing="ease-in-out"
  duration="1200"
  delay="500"
  (start)="onStartAnimation()"
  (finish)="onFinishAnimation()"
>
</animatable-component>
```
Let me know 👍

**Comment by travisryan** [comment]
I am, but the events aren't really the problem. I'm wanting to NOT use autoPlay, and fire it off myself from within the program. I can do it with the .play() on the second one, but it's like the first doesn't happen. Even if I put await both of them.

**Comment by jdnichollsc** [comment]
Yeah, very odd... I'm checking right now

**Comment by travisryan** [comment]
yeah I only put the events, so I could see when each started and stopped. Both started, but only the one that worked finished.

**Comment by jdnichollsc** [comment]
@travisryan ohh ok, it's fixed if we wait for the window to be loaded:
```
window.addEventListener('load', () => {
  animatePlayerTo.play();
});
```

Other option is `animatePlayerFrom.autoPlay = true;` 😄

**Comment by travisryan** [comment]
can I put that right in my page in ionic?

**Comment by jdnichollsc** [comment]
Yes! And check other option: https://stackoverflow.com/a/58861708/1532821

**Comment by jdnichollsc** [comment]
I added the example here => https://codepen.io/jdnichollsc/pen/MWwmBzr
@travisryan let me know if you have any other concern using it with Ionic 👍

**Comment by travisryan** [comment]
One more thing, Should this be able to work with more than one element inside? Like a div with a row of columns etc?

**Comment by travisryan** [comment]
The autoPlay kicks off with the animatePlayerFrom.autoPlay=true, but it actually kicks off twice for at least one of them, and sometimes twice for both. AND it doesn't show the affect?

```
if(self.animatePlayerTo != null)
      {
        var animatePlayerTo = document.getElementById("animate"+self.animatePlayerTo);
        console.log(animatePlayerTo);
        animatePlayerTo.addEventListener("start", function(event) {
          console.log('ANIMATION START', event)
        });
        animatePlayerTo.addEventListener("finish", function(event) {
          console.log('ANIMATION FINISH', event)
        });
        animatePlayerTo.autoPlay = true;
        //await animatePlayerTo.play();
        //self.animatePlayerTo = null;

      }
      if(self.animatePlayerFrom != null)
      {
        var animatePlayerFrom = document.getElementById("animate"+self.animatePlayerFrom);
        console.log(animatePlayerFrom);
        animatePlayerFrom.addEventListener("start", function(event2) {
          console.log('ANIMATION START', event2)
        });
        animatePlayerFrom.addEventListener("finish", function(event2) {
          console.log('ANIMATION FINISH', event2)
        });
        
        animatePlayerFrom.autoPlay = true;
        //await animatePlayerFrom.play();
        //console.log(animatePlayerFrom.firstElementChild);
        //animatePlayerFrom.firstElementChild.classList.add('backgroundAnimated');
        //animatePlayerFrom.firstElementChild.classList.add('invisible');
        
        //self.animatePlayerFrom = null;
      }
```

[https://imgur.com/RTsdJPj](https://imgur.com/RTsdJPj)

**Comment by jdnichollsc** [comment]
> One more thing, Should this be able to work with more than one element inside? Like a div with a row of columns etc?

yes, with any element with `display: block` as I know

>The autoPlay kicks off with the animatePlayerFrom.autoPlay=true, but it actually kicks off twice for at least one of them, and sometimes twice for both. AND it doesn't show the affect?

Let me verify

**Comment by jdnichollsc** [comment]
Hello mate, can you verify the last version?
Let me know 🙏

**Comment by travisryan** [comment]
still not working for me. I think it's kicking off once for each which is good, but there is no animation. 

I even made sure it's a div that is 'display: block' and that is wrapped around an img.

**Comment by jdnichollsc** [comment]
Please share a codepen updated to be able to check this issue :)

**Comment by travisryan** [comment]
if I put autoPlay in the HTML, it works fine. I'm pretty much using the same code as posted above. I want to make it work from the programming, so I want it to be there, but turn autoPlay on. I have the programming exactly as above also, and it fires off (the correct amount of times now, on the latest version) and it looks like it starts and stops from my subscriptions to the events, but I don't see any movement, etc.

**Comment by jdnichollsc** [comment]
I can't help you without the code to reproduce the issue, or please attach a github repo to be able to run locally :)

**Comment by jdnichollsc** [comment]
@travisryan in what browser are you testing?
