### ISSUE TITLE
when local run, it doesn't work

### ISSUE THREAD

**Issue by Rabbitzzc** [proyecto26/animatable-component#16]
There seems to be a problem with the local run, select different animation effects, it doesn't work

**Comment by jdnichollsc** [comment]
Can you share your code or attach a repo please?

**Comment by Rabbitzzc** [comment]
> Can you share your code or attach a repo please?

emmm, I just fork your code, and Clone to local, then execute `npm Install`.

**Comment by jdnichollsc** [comment]
Sorry, what code? Are you talking about demo-pwa project? :)

**Comment by Rabbitzzc** [comment]
> Sorry, what code? Are you talking about demo-pwa project? :)

no, just run `yarn start`

**Comment by jdnichollsc** [comment]
I don't understand, Why do you want to debug the source code of this component? Check the instructions to use it from your projects https://github.com/proyecto26/animatable-component#getting-started-
