### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by JuanSeBestia** [proyecto26/animatable-component#2]
Hi friend.

I tried too use your component in codesanbox, but couldn't make it worked correctly.
https://codesandbox.io/embed/proyecto26animatable-component-eugmg
Ad also tried in codepen
https://codepen.io/jsdussanc/pen/MWWOgXg?editors=1111

Can you help me?

**Comment by jdnichollsc** [comment]
Check bro 👍  https://codepen.io/jdnichollsc/full/rNNYBbe
